## Copyright (c) 2023, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

locals {
  resource_name_suffix        = "-helidon-ocw-hol"
  resource_name_random_suffix = "${local.resource_name_suffix}-${random_string.random_value.result}"
  # default name of Helidon MP with OCI integration application generated by the archetype
  application_repo_name       = "oci-mp"
}

#random id generation
resource "random_string" "random_value" {
  length  = 4
  special = false
}
